language: node_js
node_js:
  - "6.9.1"
cache: npm
install:
- pip install --user awscli
script:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then make deploy; fi
branches:
  only:
  - master
env:
  global:
  - secure: nNrmDyYnlZtHq+SekaXWRrUhpSppZKwzMPDZqko5EQu5+388jPhMQYloZhRf5yguuJvPCm1NjYRwOn1xSYWyowCFVQk8rgGUOqPcDu+1aS7LdMlU8VvzUh1JQvTRSoq5u2fJbq5PfSygUK3hHvaN+JKgaCFdRV3SrOeGmtrnGiGzGUkUQ6iKBBHe5MRUiAb0yAiZV/FvGhQMVElY8JCksvIjvDBHZrbxbxQ4Fzj8VC7tqqYGUIZNZL13arf0S45duajxvQjP2IccFImeVz5OMwWJdhMQp+EZdv1ydJqDy74T63vGR91rKYOr1fx09NeIEkRV26xnPD6w9gJVJaXSrBGQoG98xJszfb49tUawBjZhG+oXqDAO4TbP8H8IDCkSNysqt/pXNEvQkHbanADFnzoqQ7y6rgwvJ5aSM9b/cFC9Ca+K1HRbOSGJEHogG2jj8hsDmf+8xUHS45XuZprOxa8F7VGXMfe+gbHBe0QBJpCh/4iQbleqMsPenQqNIqRVdPYUejrawuGuYisdN8D2kzwotuQnc12OyiLl060gs0bQvKwnMNRNELOyXTj63KfUtIhGciGL/pvFfDy20y9EopQX8iDEg4zfdKn56o8/BivvQS2TB8lW8ixG5GSlItH1OC4ZpxYmIN6bGR9isfC+CI4xaypfv3RObtQg8IeVxXA=
  - secure: OJBxWOTurvcY8b59y6lWXehIaKsQacCn67FIw+po7aGuXZRnyKJd/xv+GJh0CmaivpD+gI4gf1YNRG4ZBG3slnHphw3+7GyAmZfO2Xw8+WkNte5CN25SBLgqWMin401XbAkUdjtaAGGIZinLNGXfa6Ds/00WKt6S4lrY+/akfUzC1vQZ2XTqYVoXu4khgzYD1FgV1nFFOnLOjETbcWRO9ejmchGXPEkf73HwNAkQhiNi+dFXlTjEle9fwEm4MwxXefo7Xw2ZO36jkI/6nuaOv+eGoLNmac1dvuQmi6x49hF7i1zp/++C4Dj6zixqFs4zttw3bE+np4oOM1LL9MXI1ZA1Ue1ImO+hH/Q/1NXK58QLPWEdI6lBmZonpIEbVCsmdxeQxluAzcc/Kf03y/U/Mm+1rVmYoONlnCgpPBKLTDVRpbM5Wa45M1qr+sN61KMmaJu8m0o0GA9ARNiLZ1YBXmWxWTtR89gaUdWUTqryvFfvgLHFNBaTUmvSgEZnEEZ7+so7xWYs2oV5U2jXcGi7mcJ0BJev7IBZPBYckz0h5e7kkLRIMe3pLrBrFSEHIlZA1jnT68Rvyoyyo0CKc8cPODWUl9CPuD2pTBXLrm4RGdH4qpw3YcecdqkiSjaEVAvfac9FuANFdLMro75JsR+xJ9hy7QHtITAFaRw9er76p3s=
